services:
  user-migration:
    container_name: keycloak-user-migration
    volumes:
      - ${HOST_LOGS_DIR:-./logs}:/app/logs
      - ${HOST_OUTPUT_DIR:-./output}:/app/output
    environment:
      - NODE_ENV=production
      # OpenMRS database configuration
      - OPENMRS_DB_HOST=${OPENMRS_DB_HOST}
      - OPENMRS_DB_PORT=${OPENMRS_DB_PORT}
      - OPENMRS_DB_USER=${OPENMRS_DB_USER}
      - OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD}
      - OPENMRS_DB_NAME=${OPENMRS_DB_NAME}
      # OpenMRS database configuration
      - ODOO_DB_HOST=${ODOO_DB_HOST}
      - ODOO_DB_PORT=${ODOO_DB_PORT}
      - ODOO_DB_USER=${ODOO_DB_USER}
      - ODOO_DB_PASSWORD=${ODOO_DB_PASSWORD}
      - ODOO_DB_NAME=${ODOO_DB_NAME}
      # Keycloak configuration
      - KEYCLOAK_REALM_ROLES=${KEYCLOAK_REALM_ROLES}
      - KEYCLOAK_DEFAULT_PASSWORD=${KEYCLOAK_DEFAULT_PASSWORD}
      # Paths
      - LOGS_DIR=${LOGS_DIR}
      - OUTPUT_DIR=${OUTPUT_DIR}
      # Source system to migrate
      - SOURCE_SYSTEM=${SOURCE_SYSTEM}
    image: ghcr.io/mekomsolutions/keycloak-user-migration-helper:latest
    restart: "no"
